# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://tinyzoesy.github.io'
baseurl: ''
title: 'Tiny Loafer'
description: 'Beautiful world, where are you'
permalink: pretty
logo: "/assets/logo.png"

favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logo.png'
  32: '/assets/logo.png'
  96: '/assets/logo.png'
  120: '/assets/logo.png'
  144: '/assets/logo.png'
  180: '/assets/logo.png'
  512: '/assets/logo.png'
  1024: '/assets/logo.png'

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
# - title: Home
#   url: /
- title: About
  url: /about/
- title: Blog
  url: /

# Footer nav
navigation_footer:
- title: Powered by Jeklly, Alembic
  url: https://github.com/daviddarnes/alembic

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
      
email: "zouvra@gmail.com"


fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap
    - https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;1,400
    - https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,700
